### ISSUE TITLE
Information about current capabilities

### ISSUE THREAD

**Issue by Maximus-CZ** [mikey0000/pyluba#10]
Hi, I wonder if theres a list of things the current implementation is capable of? I have tried clicking trough Wiki but apart from "mow manually at higher speed" I am at a loss. I am particulary interested in forcing Luba to mow No-Go Zone Laps in inner-first order, as opposed to outer-first order its doing now (or just make it so when user selects 1 lap around a No-Go Zone, the inner most lap gets mowed as opposed to outer most.

Is something like this possible?

In the part where you invite other people to help out with this project you mention decompiling apk, but provide no guidance how to do it. Do you reckon the issue from above might be handled entirely in phone-app side, opposed to having to flash different firmware?

Thanks for answers!

**Comment by mikey0000** [comment]
To answer your first question, most likely not. The protobuf messages don't contain an order for those. Though this could change in future. 

Decompling the app is fairly easy these days, if people want to help and don't know how to do it, they should help in other ways like fleshing out the service layers. 

Most of the protobuf messages are already written and working (by me) so you can pull data, make it go mow, turn on the blades when your not supposed to. 

The main blocker at the moment is it's Bluetooth only/MQTT (though you need a rooted phone to get the data required to make it work) . I've been at work trying to decode the last thing to work with the aliyun APIs once that's done both Bluetooth and WiFi will be options. 

Then it's just the case of creating the interfaces to home assistant etc.

You'll never manage to flash alternative firmware without 1. Writing your own and 2. Jtagging the hardware

**Comment by tom-x1** [comment]
Thanks for your effort @mikey0000 , we appreciate that! :-)

**Comment by MatMice** [comment]
Just piggybacking this thread to not open a new one, do you think we can get this to the point of being able to somehow map and remap regions (IE have more than the base limit of regions by quick swapping the data out somehow?) (I am assuming this is some sort of middleware between their servers and the app itself?)

**Comment by mikey0000** [comment]
There is no middleware, it's stored directly on the device, there are no commands (that I'm aware of) that will load and unload a map, it's all done directly on the machine. I'm not sure how mammotion storage of maps data comes into the equation but it's more than likely for debugging/r and d purposes, though could give thst a shot.

**Comment by MatMice** [comment]
Alright, well if I continue to struggle getting my Luba to do the things, I may try and help with this project in hopes to make some sort of more usable Luba. Being limited to 3 zones on my device is proving to be a huge pain for regions that are low signal, so was hoping to either push and pull maps in and out of the app/servers when needing to switch to mow the less stable regions of my yard. + any other cool things we could get this software to do. Thank you for even starting to work on a project, much love mikey0000 <3

**Comment by mikey0000** [comment]
The craziest solution is to control over Bluetooth and monitor co-ordinates and manual mow backed by some software

**Comment by MatMice** [comment]
Do you have a discord for discussion regarding this project? Ill end up putting to much garbage in issues before they probably need to be there >.<

**Comment by mikey0000** [comment]
Can open a discussion on here for now, no I don't have a discord for this specifically, just trying to think where would be appropriate.

**Comment by MatMice** [comment]
So one other problem I am trying to fix would be general alarm/tracking of the thing just in case someone decide to walk to far from my house. I know this can be achieved a few different ways, Currently I was thinking of putting an air tag on it and just listen for once its to far from a specific spot; though as well could use the other connectivity data through bluetooth or wifi I suppose to see. 

Do of any videos of people taking off the wheel caps, wondering if something could be put into there..

**Comment by mikey0000** [comment]
Plenty of space inside the case, very easy to open up
