### ISSUE TITLE
Discussion: Upgrading 3000 to 5000

### ISSUE THREAD

**Issue by jLynx** [mikey0000/pyluba#12]
I wanted to have a discussion with you lot as you may have some more knowledge around this area.
I'm keen to mod my 3000 to turn it into a 5000. As far as I'm aware, the hardware is exactly the same, it's just software/firmware that differs. So I have a few questions around this.

1.  Does the limitation such as the mowing speed come from the app side or the firmware of the Luba? (from looking around the repo, it looks to be app side?)
2. Purely theoretically would it be possible to flesh the 5000 firmware onto the 3000 to lift limitations built into it such as lifting the slope angle from 65% to 75%. That off the top of my head was the only limitation I could think of that would be built into the firmware
3. How would the app know if you have a 3000 or 5000? I assume they have a database with a serial to model map on it and that's how it's decided and then the corosponding firmware is flashed onto it. What are your thoughts?

I'm posting this question here as this is the only community I have found related to hacking around with the Luba.

**Comment by mikey0000** [comment]
1. Some limitations are app side, speed limits are a new one thst I've not investigated on other models but there is an upper limit in firmware (I've tried to exceed it)
2. In theory yes, you'd need jtagging hardware, but it is definitely possible to dump the firmware and no you can't do much over the USB last I checked, it's locked down. 
3. The model is reported from the firmware and registration.

Additionally if you modified the firmware youd have to either ignore future updates or perform the same process to change the values in firmware.

The Luba has some pretty well built systems in place for firmware updates and so on, though you do risk loosing wifi access amongst other things.

If I were you unless you are a hardware engineer or very bright/looking for a big challenge, look to replace the brain of Luba with ardupilot or similar.

Easiest way to mess with speed is to get a game pad and use the Bluetooth side of things and see how fast you can drive it, see the tests folder.

**Comment by mikey0000** [comment]
I've not got the jtagging hardware myself but if you can manage to both dump and reload the firmware, I'll see about getting the hardware and get you a dump, yes I have a 5000 beta unit but effectively the same. Perhaps flick me an email and can continue this conversation somewhere less public.

**Comment by mikey0000** [comment]
Michael@arthur.kiwi.nz
