### ISSUE TITLE
Authentication changed?

### ISSUE THREAD

**Issue by mcules** [mikey0000/pyluba#15]
Could it be that Mammotion has recently made changes to the authentication method? I can't find either the term "getSaveMobileTriple" or the access data in logcat. I can only find a JSON string containing information about the MQTT broker URL.

**Comment by mcules** [comment]
Do you have an idea how to get the auth data now?

**Comment by mikey0000** [comment]
what do you mean auth data? Do you want the MQTT tokens? do you just want the auth tokens from the mammotion servers? or do you want auth for the alibaba/aliyun IOT servers? You're going to have to be a bit clearer, what are you trying to achieve?

**Comment by mcules** [comment]
Sure, I'd like to log in to the MQTT broker and check out the data stored there. It seems like the method outlined in the wiki (https://github.com/mikey0000/pyluba/wiki/MQTT) isn't functioning anymore.

**Comment by mikey0000** [comment]
Thanks for the clarification. you could try using hmacsha256 and see if that works. I'll need some time to go back and review their MQTT implementation, alternatively you could sniff the http requests off a rooted android device and see if anything has changed/ get the tokens directly from there.

**Comment by mikey0000** [comment]
I'm still working on a full flow from login to MQTT tokens. the encryption pattern for aliyun isn't straightforward and is fairly clever.

**Comment by mcules** [comment]
Thank you for your response. Unfortunately, I don't have access to a rooted Android device. I'll see if I can emulate something meaningful in the next few days. Using MQTT for this would definitely be better than constantly having to send POST requests. ;)

**Comment by mikey0000** [comment]
I'm now curious as to what your up to?

**Comment by MAVProxyUser** [comment]
Is there still a path to obtain the Aliyun token?

**Comment by mikey0000** [comment]
Rooted android device.... For now. Would be good to know how your using MQTT as I (and others) expand this library.

**Comment by mikey0000** [comment]
> Thank you for your response. Unfortunately, I don't have access to a rooted Android device. I'll see if I can emulate something meaningful in the next few days. Using MQTT for this would definitely be better than constantly having to send POST requests. ;)

Your using POST requests to get data?

**Comment by MAVProxyUser** [comment]
Any chance you have the dropbear ssh password for port 33089 on Luba2?

**Comment by mikey0000** [comment]
nope, sorry, pretty sure the app doesn't use that port at all.

**Comment by MAVProxyUser** [comment]
Nah I don't think it does, but obviously getting into the bot, will give us a better understanding of the API.

**Comment by mikey0000** [comment]
> Nah I don't think it does, but obviously getting into the bot, will give us a better understanding of the API.

The api is well understood by me at least. No need to get into the robot. Only thing I haven't done is mitm the WiFi connection from Luba to router
